const API=window.location.origin;
async function api(p,o={}){const r=await fetch(API+p,{...o,credentials:"include",headers:{"Content-Type":"application/json",...(o.headers||{})}});const d=await r.json().catch(()=>({message:"پاسخ نامعتبر"}));if(!r.ok)throw Error(d.message||"خطا");return d}
function e(v){return String(v??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]))}
async function login(){try{await api("/api/admin/login",{method:"POST",body:JSON.stringify({password:document.getElementById("adminKey").value})});document.getElementById("loginCard").hidden=true;document.getElementById("panel").hidden=false;await loadAll()}catch(x){alert(x.message)}}
async function logout(){await api("/api/admin/logout",{method:"POST"});location.reload()}
async function loadHealth(){try{const d=await fetch(API+"/api/health").then(r=>r.json());document.getElementById("health").textContent=d.ok?"متصل":"خطا"}catch{document.getElementById("health").textContent="عدم اتصال"}}
async function loadCodes(){const d=await api("/api/admin/codes");document.getElementById("codes").innerHTML="<table><tr><th>کد</th><th>پایه</th><th>سال</th><th>وضعیت</th><th>زمان</th></tr>"+d.codes.map(x=>"<tr><td>"+e(x.codePreview)+"</td><td>"+e(x.gradeId)+"</td><td>"+e(x.academicYear)+"</td><td>"+e(x.status)+"</td><td>"+e(x.createdAt)+"</td></tr>").join("")+"</table>"}
async function loadLicenses(){const d=await api("/api/admin/licenses");document.getElementById("licenses").innerHTML="<table><tr><th>مجوز</th><th>پروفایل</th><th>پایه</th><th>سال</th><th>اعتبار تا</th><th>وضعیت</th></tr>"+d.licenses.map(x=>"<tr><td>"+e(x.licenseId)+"</td><td>"+e(x.studentId)+"</td><td>"+e(x.gradeId)+"</td><td>"+e(x.academicYear)+"</td><td>"+e(x.validUntil)+"</td><td>"+e(x.status)+"</td></tr>").join("")+"</table>"}
async function revokeLicense(){try{await api("/api/admin/licenses/revoke",{method:"POST",body:JSON.stringify({licenseId:document.getElementById("licenseIdAction").value.trim()})});await loadLicenses();alert("مجوز لغو شد.")}catch(x){alert(x.message)}}
async function extendLicense(){try{const v=document.getElementById("extendUntil").value;if(!v)throw Error("تاریخ پایان را وارد کنید.");await api("/api/admin/licenses/extend",{method:"POST",body:JSON.stringify({licenseId:document.getElementById("licenseIdAction").value.trim(),validUntil:new Date(v).toISOString()})});await loadLicenses();alert("مجوز تمدید شد.")}catch(x){alert(x.message)}}
async function loadPayments(){const d=await api("/api/admin/payments");document.getElementById("payments").innerHTML="<table><tr><th>شناسه</th><th>درگاه</th><th>وضعیت</th><th>مبلغ</th><th>پایه</th><th>سال</th><th>زمان</th></tr>"+d.payments.map(x=>"<tr><td>"+e(x.paymentId)+"</td><td>"+e(x.provider)+"</td><td>"+e(x.status)+"</td><td>"+e(x.amount)+" "+e(x.currency)+"</td><td>"+e(x.gradeId)+"</td><td>"+e(x.academicYear)+"</td><td>"+e(x.createdAt)+"</td></tr>").join("")+"</table>"}
async function loadAudit(){const d=await api("/api/admin/audit");document.getElementById("audit").innerHTML="<table><tr><th>رویداد</th><th>عامل</th><th>مجوز</th><th>زمان</th></tr>"+d.audit.map(x=>"<tr><td>"+e(x.eventType)+"</td><td>"+e(x.actor)+"</td><td>"+e(x.licenseId)+"</td><td>"+e(x.createdAt)+"</td></tr>").join("")+"</table>"}
async function createCodes(){try{const d=await api("/api/admin/codes",{method:"POST",body:JSON.stringify({gradeId:document.getElementById("grade").value,academicYear:document.getElementById("year").value,count:Number(document.getElementById("count").value)})});document.getElementById("newCodes").textContent=d.codes.join("\n");await loadCodes()}catch(x){alert(x.message)}}
async function loadAll(){await loadHealth();try{await loadCodes();await loadLicenses();await loadPayments();await loadAudit()}catch(x){alert(x.message)}}
loadHealth();
async function searchAll(){try{const q=encodeURIComponent(document.getElementById("searchQ").value.trim());const d=await api("/api/admin/search?q="+q);document.getElementById("searchResults").innerHTML="<h3>مجوزها</h3>"+(d.licenses.length?d.licenses.map(v=>"<div>"+e(v.licenseId)+" | "+e(v.studentId)+" | "+e(v.gradeId)+" | "+e(v.status)+"</div>").join(""):"موردی پیدا نشد")+"<h3>کدها</h3>"+(d.codes.length?d.codes.map(v=>"<div>"+e(v.codePreview)+" | "+e(v.gradeId)+" | "+e(v.status)+"</div>").join(""):"موردی پیدا نشد")}catch(z){alert(z.message)}}
