// =====================================
// Tahouri Edu Platform
// Welcome Manager v3.0
//
// Purpose:
// - Keep the active profile name in the Dashboard greeting
// - Place "سلام [نام] عزیز" beside "یک جمله برای تو"
// - Keep the profile button as "👤 پروفایل من"
// - Do not alter Continue Learning
// - Do not alter Quiz / Memory / Reports / Dashboard logic
// =====================================


const WelcomeManager = {

    VERSION: "3.0",


    getActiveProfileName: function () {

        try {

            if (
                typeof ProfileManager !== "undefined" &&
                typeof ProfileManager.get === "function"
            ) {

                const profile = ProfileManager.get();

                if (
                    profile &&
                    typeof profile.name === "string" &&
                    profile.name.trim()
                ) {

                    return profile.name.trim();

                }

            }

        }
        catch (error) {

            console.error(
                "WelcomeManager: Profile read failed",
                error
            );

        }

        return "دانش‌آموز";

    },


    // =====================================
    // HOME
    // =====================================

    personalizeHome: function () {

        const app = document.getElementById("app");

        if (!app) {

            return;

        }

        const heading = app.querySelector(".screen > h1");
        const greeting = heading
            ? heading.nextElementSibling
            : null;

        if (
            greeting &&
            greeting.tagName === "P" &&
            !greeting.dataset.welcomeManaged
        ) {

            greeting.textContent =
                `سلام ${this.getActiveProfileName()} عزیز 🌷`;

            greeting.dataset.welcomeManaged = "true";

        }

    },


    // =====================================
    // DASHBOARD
    // =====================================

    personalizeDashboard: function () {

        const dashboard =
            document.querySelector(".dashboard-screen");

        if (!dashboard) {

            return;

        }

        // Do not run twice.
        if (
            dashboard.querySelector(
                ".dashboard-welcome-message-row"
            )
        ) {

            return;

        }

        const welcome =
            dashboard.querySelector(".dashboard-welcome");

        const message =
            dashboard.querySelector(".dashboard-message");

        if (!welcome || !message) {

            return;

        }

        const messageCard =
            message.closest(".dashboard-card");

        if (!messageCard) {

            return;

        }

        // The greeting is generated by dashboardScreen.
        // Replace its text with the active profile name and
        // then physically place that existing block beside
        // the daily-message card.
        const heading =
            welcome.querySelector("h1");

        if (heading) {

            heading.textContent =
                `👋 سلام ${this.getActiveProfileName()} عزیز`;

        }

        // Remove the standalone separator belonging to the
        // old greeting position.
        const separator = welcome.nextElementSibling;

        if (
            separator &&
            separator.tagName === "HR"
        ) {

            separator.remove();

        }

        const row =
            document.createElement("div");

        row.className =
            "dashboard-welcome-message-row";

        row.appendChild(welcome);
        row.appendChild(messageCard);

        // Insert the row at the original dashboard greeting
        // position. Calendar and Continue Learning remain
        // exactly where DashboardScreen rendered them.
        const firstCard =
            dashboard.querySelector(".learning-calendar-card");

        if (firstCard) {

            dashboard.insertBefore(row, firstCard);

        }
        else {

            dashboard.insertBefore(row, dashboard.firstChild);

        }

        // The profile control must never contain the student's name.
        const profileButton =
            document.getElementById("profileBtn");

        if (profileButton) {

            profileButton.textContent = "👤 پروفایل من";

        }

        console.log(
            "WelcomeManager v3.0: Dashboard greeting placed beside daily message",
            {
                profileName: this.getActiveProfileName()
            }
        );

    },


    // =====================================
    // DASHBOARD CSS
    // =====================================

    styles: function () {

        const styleId =
            "tahouriWelcomeManagerV3Styles";

        if (document.getElementById(styleId)) {

            return;

        }

        const style = document.createElement("style");

        style.id = styleId;

        style.textContent = `

            .dashboard-welcome-message-row {

                display: grid;

                grid-template-columns:
                    minmax(0, 1fr)
                    minmax(0, 1.4fr);

                gap: 15px;

                width: 100%;

                margin: 0 0 18px 0;

                align-items: stretch;

            }


            .dashboard-welcome-message-row .dashboard-welcome,
            .dashboard-welcome-message-row .dashboard-card {

                box-sizing: border-box;

                width: 100%;

                min-width: 0;

                height: 100%;

                margin: 0;

            }


            .dashboard-welcome-message-row .dashboard-welcome {

                padding: 18px;

                border-radius: 12px;

                background: #ffffff;

                border: 1px solid #e1e4e8;

            }


            .dashboard-welcome-message-row .dashboard-welcome h1 {

                margin-top: 0;

            }


            @media (max-width: 700px) {

                .dashboard-welcome-message-row {

                    grid-template-columns: 1fr;

                    gap: 10px;

                }

            }

        `;

        document.head.appendChild(style);

    },


    // =====================================
    // WATCH APP RENDERING
    // =====================================

    observe: function () {

        const app = document.getElementById("app");

        if (!app || this.observer) {

            return;

        }

        this.styles();

        const process = function () {

            WelcomeManager.personalizeHome();
            WelcomeManager.personalizeDashboard();

        };

        this.observer =
            new MutationObserver(function () {

                process();

            });

        this.observer.observe(
            app,
            {
                childList: true,
                subtree: true
            }
        );

        process();

    },


    // =====================================
    // INIT
    // =====================================

    init: function () {

        this.observe();

        console.log(
            "WelcomeManager v3.0 Ready"
        );

    }

};


WelcomeManager.init();
